{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tbyte-microservices.fullname" . }}-frontend
  labels:
    {{- include "tbyte-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tbyte-microservices.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
